### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FredericVincent0** [MatthewL246/pretendo-docker#129]
![Capture d’écran (4)](https://github.com/user-attachments/assets/0bc81c87-1a1a-4114-8fbf-8b03e9f85b49)

**Comment by MatthewL246** [comment]
I think this error is due to the `core.autocrlf` setting in Git for Windows, which changes the line endings of files in repos when you clone them. Please check the "Tips for Windows users" section [in the docs](https://matthewl246.github.io/pretendo-docker/setup/server-setup#downloading). Using Git Bash in Windows is not recommended because of this. I suggest re-cloning the repo using Bash and Git installed inside your WSL repo, not Git Bash.

**Comment by MatthewL246** [comment]
Disregard that comment I deleted, it is spam and the file linked is most likely malware.

**Comment by FredericVincent0** [comment]
but i cant understand

**Comment by FredericVincent0** [comment]
ok no its ok i think i understand
![Capture d’écran (5)](https://github.com/user-attachments/assets/7a3aefdf-4827-476e-8b09-f5be87767b87)

**Comment by MatthewL246** [comment]
That looks good to me. I just made a minor wording update to the docs in 0909a20fbfc7f8a8733c931eaeccf6e91a32ba38 to clarify this point.

**Comment by FredericVincent0** [comment]
btw i got error when i generate fake online file

**Comment by FredericVincent0** [comment]
![Capture d’écran (6)](https://github.com/user-attachments/assets/a0db36e0-0489-4ae0-98ca-4517035a39ca)

**Comment by FredericVincent0** [comment]
![Capture d’écran (7)](https://github.com/user-attachments/assets/294b1a89-ff25-4537-bb9a-11aeecd94220)

**Comment by FredericVincent0** [comment]
the account exist

**Comment by MatthewL246** [comment]
It looks like you're trying to use an account from Pretendo's official servers? That won't work, you need to create an account on your self-hosted server because, by design, a self-hosted server has no connection to the official servers.

**Comment by FredericVincent0** [comment]
How i Do that?

Le jeu. 5 sept. 2024, 13 h 13, Matthew Lopez ***@***.***> a
écrit :

**Comment by MatthewL246** [comment]
[Connect a web browser to your server](https://matthewl246.github.io/pretendo-docker/setup/connecting/).

**Comment by FredericVincent0** [comment]
![Capture d’écran (8)](https://github.com/user-attachments/assets/ef02ae88-eb6b-48ad-9cf4-bdf2e9a2e0ca)

**Comment by FredericVincent0** [comment]
ok nvm i restart docker and it work

**Comment by FredericVincent0** [comment]
ok i finally did it thanks you i close for real this time
