### ISSUE TITLE
[Cemu & BOSS] BOSS not honoring proxy settings.

### ISSUE THREAD

**Issue by AToska21** [MatthewL246/pretendo-docker#136]
Thought I'd make this issue so people would know and not clutter up the issues tab.
In the current experimental build of Cemu, the BOSS implementation is bugged, and it won't follow the proxy_server in settings.xml.
I've talked to the Cemu devs and it seems they may fix it in the latest build, but that may be a while.
For now, you can patch it yourself by adding the following piece of code after `curl = std::shared_ptr<CURL>(curl_easy_init(), curl_easy_cleanup);` in `src/Cafe/IOSU/legacy/iosu_boss.cpp`:
```cpp
			if(GetConfig().proxy_server.GetValue() != "")
			{
			  curl_easy_setopt(curl.get(), CURLOPT_PROXY, GetConfig().proxy_server.GetValue().c_str());
			}
```
Then you can build through GitHub Actions.

**Comment by AToska21** [comment]
This is now resolved in Cemu's codebase. You might have to wait for the next experimental build or just use the [latest actions build](https://github.com/cemu-project/Cemu/actions/runs/10882175769).

**Comment by MatthewL246** [comment]
This might be the cause of #56, will need to check if the new build fixes that.

**Comment by AToska21** [comment]
> This might be the cause of #56, will need to check if the new build fixes that.

Yeah that's what caused me to create this issue too, had issues with Splatoon.
