### ISSUE TITLE
Failed to receive latest news data

### ISSUE THREAD

**Issue by Leahnaya** [MatthewL246/pretendo-docker#138]
I am trying to get Splatoon working, and when I get to the "To participate in online battles, you need to connect to the internet and receive the latest News data." page, I'll hit receive, but then it gives an error that it cannot connect to the server.

Looking at the MITM logs, there is a 400 and a 404 that happen after clicking "Receive", but I'm not sure what is causing those.

These are all the log lines from Wii U startup, through trying to receive news:
![image](https://github.com/user-attachments/assets/4b2efb48-a9ee-4010-8355-0791e9cfbbb1)

**Comment by MatthewL246** [comment]
Are there any logs from the Splatoon server?

```
docker compose logs splatoon
```

The 400 from `api.olv.pretendo.cc` is from the Miiverse API, and you should be able to get more information on that with `docker compose logs miiverse-api`. I don't think this is required to load Splatoon though, so it is probably an unrelated error. `npvk.app.pretendo.cc` is a service that Pretendo hasn't implemented support for yet, and it isn't required by the game.

**Comment by Leahnaya** [comment]
Here is the logs from running that:
`leahnaya@OptiPlex-7450-AIO:~/pretendo-docker$ docker compose logs splatoon
splatoon-1  | 2024-09-21T17:46:59Z warning layer=rpc Listening for remote connections (connections are not authenticated nor encrypted)
splatoon-1  | 2024-09-21T17:46:59Z info layer=debugger launching process with args: [./server]
splatoon-1  | API server listening at: [::]:2345
splatoon-1  | 2024-09-21T17:47:00Z debug layer=debugger Adding target 11 "/home/go/app/server"
splatoon-1  | 2024-09-21T17:47:00Z debug layer=debugger continuing
splatoon-1  | 2024-09-21T17:47:00Z debug layer=debugger ContinueOnce
splatoon-1  | [2024-09-21T17:47:00] [WARNING]  [func 0() main.init/init.go:25] : Error loading .env file
splatoon-1  | 
`

**Comment by Leahnaya** [comment]
The splatoon.env file exists at /home/leahnaya/pretendo-docker/environment and contains:
```
MONGO_URI=mongodb://mongodb:27017/pretendo_account?replicaSet=rs
PN_SPLATOON_AUTHENTICATION_SERVER_PORT=6006
PN_SPLATOON_SECURE_SERVER_PORT=6007
PN_SPLATOON_ACCOUNT_GRPC_HOST=account
PN_SPLATOON_ACCOUNT_GRPC_PORT=5000
```

**Comment by MatthewL246** [comment]
That's an expected warning - the server can load its configuration from either environment variables or a .env file. Pretendo Docker uses environment variables because that's easier to set up for a Docker container, but both methods work identically.

I'm not sure why this error is occurring, I'll look into this further. It seems like there are a few issues with Splatoon, judging by #135.

**Comment by Leahnaya** [comment]
Okay, so I did a full reset of the server (deleted and recloned everything) and looks like we made some progress.  It looks like it isn't able to grab the rotation data (I recognize this tasksheet having to do with it).
![image](https://github.com/user-attachments/assets/b623afdf-076e-4905-a811-c8bdf5229d59)

@MatthewL246 How do I upload a new tasksheet for it to grab?

**Comment by MatthewL246** [comment]
That's not something I've tested, unfortunately, but I believe this is the same thing as #134. I sent some basic information there about the tasksheet and rotations. Hopefully, those help for now.

Once I've tested the schedule upload process, I'll add a script to automate it since it's so important for Splatoon.

**Comment by AToska21** [comment]
you need to copy the "cdn" folder from the build to the final image in the dockerfile.

**Comment by AToska21** [comment]
> I have the exact same issue with a fresh install of pretendo-docker. @AToska21 I'm not really familiar with pretendo's architecture (and docker is not really mt cup of tea :) ). Can you be more specific about CDN folder and where find it ? Thanks ;)

repos/BOSS/cdn
