### ISSUE TITLE
not really an issue just a feature request

### ISSUE THREAD

**Issue by erew70** [MatthewL246/pretendo-docker#156]
it would be really nice if we could select what servers we want, so we dont have to install them all and delete ones we dont need, for example i only have 3ds so i dont have any use for pikmin 3, pokken tournament, etc

**Comment by MatthewL246** [comment]
I completely agree that this would be useful, and I've already put this in the "Larger tasks" section of the roadmap (#50). Closing because this is already being tracked there.
