### ISSUE TITLE
Command caracters not found Minio

### ISSUE THREAD

**Issue by 00cedke** [MatthewL246/pretendo-docker#158]
Hello, sorry for disturb but i have a error when i start the setup.sh, i do the all stages but i have a a problem and i don't know how to fix it, if you can help me please, thanks.
![Capture](https://github.com/user-attachments/assets/93bb6201-a99a-4574-afe2-9259f4fb8513)

**Comment by MatthewL246** [comment]
The "\r" character appearing means that the script contains Windows line endings, so it won't run correctly. Check the [Tips for Windows Users](https://matthewl246.github.io/pretendo-docker/setup/server-setup#downloading) in the docs for more information. It should work if you re-clone the repo following the tip.

**Comment by 00cedke** [comment]
I following the tip..

**Comment by 00cedke** [comment]
i have WSL on windows but when i open it, the WSL closes by itself.

**Comment by MatthewL246** [comment]
Unfortunately, that sounds like an issue with your WSL setup. Another forum like [Superuser](https://superuser.com/) could probably help with that better than I can.

**Comment by 00cedke** [comment]
i installed ubuntu apps on windows with `sudo apt install wsl` command on ubuntu, worked with that ?

**Comment by 00cedke** [comment]
i have an error because my computer with taht `run_verbose docker compose exec postgres sh -c "$postgres_init_script"`.
