### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by 00cedke** [MatthewL246/pretendo-docker#159]
I have an error here with Mongoose, column database and maybe node.
![image](https://github.com/user-attachments/assets/9c6b1908-6155-4412-a646-f4cf21836077)

**Comment by MatthewL246** [comment]
None of those are errors that prevent the script from completing, so everything looks fine to me. Those are just warnings and notices that can be safely ignored.

**Comment by 00cedke** [comment]
okay thanks for you reponse.
