### ISSUE TITLE
Add Pretendo nncs

### ISSUE THREAD

**Issue by 00cedke** [MatthewL246/pretendo-docker#162]
Hello!, I would like to propose the addition of Pretendo NNCS server for have Pretendo NAT Checker.

**Comment by AToska21** [comment]
I'd say this is out of scope for this project, as NNCS requires you have 2 seperate servers with 2 seperate IPs.

**Comment by 00cedke** [comment]
Ah

**Comment by MatthewL246** [comment]
I agree with @AToska21. This project is designed to make running a Pretendo server as simple as possible, and I do not believe there is any simple way to run a server on two separate servers using just Docker Compose and a setup script. Additionally, not everyone will necessarily have two servers. For the sake of simplicity, it makes more sense to piggyback off Pretendo's hosted NNCS servers, and there is not really much of a reason to self-host NNCS considering it's not connected to any other services or databases.

**Comment by 00cedke** [comment]
Too bad, thanks anyway lol.
