### ISSUE TITLE
How to use pretendo-docker on Wii U ?

### ISSUE THREAD

**Issue by 00cedke** [MatthewL246/pretendo-docker#163]
Hello, sorry for disturb but who can help me for use pretendo-docker to my Wii U please ? Thanks.

**Comment by MatthewL246** [comment]
The instructions for setting this up with a Wii U are already covered in the [Wii U connecting guide](https://matthewl246.github.io/pretendo-docker/setup/connecting/wiiu).

If you're having a specific issue with the guide, please reopen this and let me know what the issue is.

**Comment by 00cedke** [comment]
But can we use P¨retendo-docker in local ? without need VPS or Server.

**Comment by MatthewL246** [comment]
Yes, there is no need for a VPS. You just need to run Pretendo Docker on any Windows/Linux/MacOS computer in your home network.

**Comment by 00cedke** [comment]
Okay but idk how to run pretendo-docker local on my Wii U.. Idk if i need to add my localhost ip on my Wii U (127.0.0.1) or the ip of my computer (added on pretendo-docker with) ?

**Comment by MatthewL246** [comment]
Are you asking how to run the servers directly on the console? That is simply not possible because there is no way to run Docker on the console itself. You will need some sort of computer to run Docker.

**Comment by 00cedke** [comment]
No, not that, I would like to know how to get the Wii U to connect to the pretendo-docker which is on my PC, if on the Wii U I have to put the IP of my PC or put 127.0.0.1 or something else

**Comment by MatthewL246** [comment]
Ah, alright. Use the IP address of your PC.

**Comment by 00cedke** [comment]
I put it on Proxy or DNS ?

**Comment by MatthewL246** [comment]
Proxy. This is already explained in the docs.

**Comment by 00cedke** [comment]
Okay thanks

**Comment by 00cedke** [comment]
Oh and last thing, when i go to ipconfig, i have 3 IPv4 config, i can't know what is my real PC IP.

**Comment by 00cedke** [comment]
![image](https://github.com/user-attachments/assets/526e7f06-5322-46c6-ba6d-14c7812892f0)

**Comment by 00cedke** [comment]
doesn't work, Wii U say the wifi work but internet doesn't work, i use 192.168.1.xx (my ipv4 pc) and i used the port 8888.

**Comment by 00cedke** [comment]
Ok finally it's worked i guess with port 80, im stupid, thanks for help, have good day and sorry for the stupid question before.

**Comment by MatthewL246** [comment]
You should use port 8080, not 8888. Again, this is explicitly mentioned in the connecting guide.

**Comment by 00cedke** [comment]
Ah Ok

**Comment by 00cedke** [comment]
Worked but i have an error when i go to account creation.
