### ISSUE TITLE
Nintendo CA G3 SSL Patch Error

### ISSUE THREAD

**Issue by 00cedke** [MatthewL246/pretendo-docker#164]
![image](https://github.com/user-attachments/assets/8f373e9e-4e82-4346-8473-365d1044e044)

**Comment by MatthewL246** [comment]
The "Tips for Windows Users" section of the docs already explains that you should clone the repo inside WSL and run all of the scripts from the WSL Bash prompt. Otherwise, you will face issues like this, where `C:\...` is not a valid Linux path.

**Comment by 00cedke** [comment]
work with Ubuntu app on windows ?

**Comment by MatthewL246** [comment]
Yes, the Ubuntu app is how you launch WSL.

**Comment by 00cedke** [comment]
ty
