### ISSUE TITLE
Anticheat System

### ISSUE THREAD

**Issue by Volcan4436** [MatthewL246/pretendo-docker#178]
A potential Cheat Detector or Ban Wave Feature would be nice

**Comment by MatthewL246** [comment]
Thanks for the suggestion. However, I would consider this out-of-scope for Pretendo Docker.

This project is intended to help with self-hosting private, small-scale Pretendo servers for development purposes or online play with a small group. It is not intended for large-scale hosts where an anticheat would be relevant - it is more intended for an "if you don't trust them to play fair, don't give them access to your private server" situation. Additionally, adding completely new features on top of Pretendo is not a goal of this project. The goal is just to make self-hosting easier by integrating common open-source software and some simple scripts.
