### ISSUE TITLE
Bug file gm9

### ISSUE THREAD

**Issue by GotazHack** [MatthewL246/pretendo-docker#3]
I have a bug where when I run the script on gm9, I get "line 179: mount fail imgmount $[KEY_DB]"

**Comment by MatthewL246** [comment]
Interesting. That key dumper script was made by the Citra devs for dumping keys for the emulator. According to [their guide](https://citra-emu.org/wiki/aes-keys/), that means you might be on an end 3DS firmware or boot9strap version. 

Try making sure that your system firmware, boot9strap, Luma3DS, and GodMode9 are all fully up to date. If that doesn't work, you should ask for support in a Citra community - they're the experts in this.

**Comment by MatthewL246** [comment]
I'm going to close this because it isn't really an issue with this repo.
