### ISSUE TITLE
Eshop planned?

### ISSUE THREAD

**Issue by scoutante112** [MatthewL246/pretendo-docker#42]
Is it planned to try to solve some kind of shop so you can download games from there or what does the plan look like?

**Comment by MatthewL246** [comment]
Running the eshop and NUS servers is planned, but it is lower priority than the game servers. It would download homebrew apps instead of games to avoid piracy.

**Comment by scoutante112** [comment]
Yes, I understand. Must say this project is awesome, just want to make a little server for some mates and this makes it possible. Thanks!
