### ISSUE TITLE
Running MongoDB on a separate server

### ISSUE THREAD

**Issue by scoutante112** [MatthewL246/pretendo-docker#45]
I've been trying to get the system up and running for about 2 days now, but when I try to run it, I get "Waiting for mongodb to be ready...".
What could this be due to?

**Comment by scoutante112** [comment]
Okay. I went into my mongodb logs and get this.
`mongodb-1  | {"t":{"$date":"2024-04-22T14:04:48.947+00:00"},"s":"I",  "c":"NETWORK",  "id":4915701, "ctx":"-","msg":"Initialized wire specification","attr":{"spec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":17},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":17},"outgoing":{"minWireVersion":6,"maxWireVersion":17},"isInternalClient":true}}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:48.949+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:48.952+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:48.954+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationDonorService","namespace":"config.tenantMigrationDonors"}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:48.954+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationRecipientService","namespace":"config.tenantMigrationRecipients"}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:48.954+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"ShardSplitDonorService","namespace":"config.tenantSplitDonors"}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:48.955+00:00"},"s":"I",  "c":"CONTROL",  "id":5945603, "ctx":"main","msg":"Multi threading initialized"}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:48.955+00:00"},"s":"I",  "c":"CONTROL",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"015bd5a10fed"}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:48.956+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"6.0.5","gitVersion":"nogitversion","openSSLVersion":"OpenSSL 1.1.1n  15 Mar 2022","modules":[],"allocator":"tcmalloc","environment":{"distarch":"x86_64","target_arch":"x86_64"}}}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:48.956+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"PRETTY_NAME=\"Debian GNU/Linux 11 (bullseye)\"","version":"Kernel 6.2.0-39-generic"}}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:48.956+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"config":"/etc/mongod.conf","net":{"bindIp":"0.0.0.0","port":27017},"replication":{"oplogSizeMB":2000,"replSet":"rs"},"storage":{"dbPath":"/data/db"}}}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:48.957+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/data/db","storageEngine":"wiredTiger"}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:48.957+00:00"},"s":"I",  "c":"STORAGE",  "id":22297,   "ctx":"initandlisten","msg":"Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem","tags":["startupWarnings"]}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:48.958+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=3454M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,remove=true,path=journal,compressor=snappy),builtin_extension_config=(zstd=(compression_level=6)),file_manager=(close_idle_time=600,close_scan_interval=10,close_handle_minimum=2000),statistics_log=(wait=0),json_output=(error,message),verbose=[recovery_progress:1,checkpoint_progress:1,compact_progress:1,backup:0,checkpoint:0,compact:0,evict:0,history_store:0,recovery:0,rts:0,salvage:0,tiered:0,timestamp:0,transaction:0,verify:0,log:0],"}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.412+00:00"},"s":"I",  "c":"STORAGE",  "id":4795906, "ctx":"initandlisten","msg":"WiredTiger opened","attr":{"durationMillis":1454}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.412+00:00"},"s":"I",  "c":"RECOVERY", "id":23987,   "ctx":"initandlisten","msg":"WiredTiger recoveryTimestamp","attr":{"recoveryTimestamp":{"$timestamp":{"t":0,"i":0}}}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.422+00:00"},"s":"W",  "c":"CONTROL",  "id":22120,   "ctx":"initandlisten","msg":"Access control is not enabled for the database. Read and write access to data and configuration is unrestricted","tags":["startupWarnings"]}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.422+00:00"},"s":"W",  "c":"CONTROL",  "id":5123300, "ctx":"initandlisten","msg":"vm.max_map_count is too low","attr":{"currentValue":65530,"recommendedMinimum":1677720,"maxConns":838860},"tags":["startupWarnings"]}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.423+00:00"},"s":"I",  "c":"REPL",     "id":5853300, "ctx":"initandlisten","msg":"current featureCompatibilityVersion value","attr":{"featureCompatibilityVersion":"unset","context":"startup"}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.423+00:00"},"s":"I",  "c":"STORAGE",  "id":5071100, "ctx":"initandlisten","msg":"Clearing temp directory"}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.430+00:00"},"s":"I",  "c":"CONTROL",  "id":20536,   "ctx":"initandlisten","msg":"Flow Control is enabled on this deployment"}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.430+00:00"},"s":"I",  "c":"FTDC",     "id":20625,   "ctx":"initandlisten","msg":"Initializing full-time diagnostic data capture","attr":{"dataDirectory":"/data/db/diagnostic.data"}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.437+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"ReadConcernMajorityNotAvailableYet: Read concern majority reads are currently not possible.","nextWakeupMillis":200}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.437+00:00"},"s":"I",  "c":"REPL",     "id":6015317, "ctx":"initandlisten","msg":"Setting new configuration state","attr":{"newState":"ConfigStartingUp","oldState":"ConfigPreStart"}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.437+00:00"},"s":"I",  "c":"REPL",     "id":6005300, "ctx":"initandlisten","msg":"Starting up replica set aware services"}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.439+00:00"},"s":"I",  "c":"REPL",     "id":4280500, "ctx":"initandlisten","msg":"Attempting to create internal replication collections"}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.442+00:00"},"s":"I",  "c":"REPL",     "id":4280501, "ctx":"initandlisten","msg":"Attempting to load local voted for document"}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.442+00:00"},"s":"I",  "c":"REPL",     "id":21311,   "ctx":"initandlisten","msg":"Did not find local initialized voted for document at startup"}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.442+00:00"},"s":"I",  "c":"REPL",     "id":4280502, "ctx":"initandlisten","msg":"Searching for local Rollback ID document"}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.444+00:00"},"s":"I",  "c":"REPL",     "id":21529,   "ctx":"initandlisten","msg":"Initializing rollback ID","attr":{"rbid":3}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.445+00:00"},"s":"I",  "c":"REPL",     "id":21313,   "ctx":"initandlisten","msg":"Did not find local replica set configuration document at startup","attr":{"error":{"code":47,"codeName":"NoMatchingDocument","errmsg":"Did not find replica set configuration document in local.system.replset"}}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.445+00:00"},"s":"I",  "c":"REPL",     "id":6015317, "ctx":"initandlisten","msg":"Setting new configuration state","attr":{"newState":"ConfigUninitialized","oldState":"ConfigStartingUp"}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.445+00:00"},"s":"I",  "c":"STORAGE",  "id":22262,   "ctx":"initandlisten","msg":"Timestamp monitor starting"}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.448+00:00"},"s":"I",  "c":"CONTROL",  "id":20714,   "ctx":"LogicalSessionCacheRefresh","msg":"Failed to refresh session cache, will try again at the next refresh interval","attr":{"error":"NotYetInitialized: Replication has not yet been configured"}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.449+00:00"},"s":"I",  "c":"REPL",     "id":40440,   "ctx":"initandlisten","msg":"Starting the TopologyVersionObserver"}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.449+00:00"},"s":"I",  "c":"CONTROL",  "id":20712,   "ctx":"LogicalSessionCacheReap","msg":"Sessions collection is not set up; waiting until next sessions reap interval","attr":{"error":"NamespaceNotFound: config.system.sessions does not exist"}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.449+00:00"},"s":"I",  "c":"REPL",     "id":40445,   "ctx":"TopologyVersionObserver","msg":"Started TopologyVersionObserver"}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.450+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"/tmp/mongodb-27017.sock"}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.450+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"0.0.0.0"}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.450+00:00"},"s":"I",  "c":"NETWORK",  "id":23016,   "ctx":"listener","msg":"Waiting for connections","attr":{"port":27017,"ssl":"off"}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:50.638+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":400}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:51.039+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":600}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:51.639+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":800}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:52.441+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":1000}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:53.443+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":1200}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:54.645+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":1400}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:56.047+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":1600}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:57.647+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":1800}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:04:59.450+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":2000}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:05:01.453+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":2200}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:05:03.656+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":2400}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:05:06.059+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":2600}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:05:08.661+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":2800}}
mongodb-1  | {"t":{"$date":"2024-04-22T14:05:11.465+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":3000}}
`

I'm really bad at mongodb so apologies for being really bad at it

**Comment by MatthewL246** [comment]
Seems like this is an error in setting up MongoDB as a replica set, which Pretendo requires. Since it sounds like you don't have any important data stored yet, try shutting down the server with `docker compose down`, deleting the MongoDB database with `docker volume rm pretendo-network_mongodb-database`, and re-running the setup script. Please keep the `>/dev/null 2>&1` in `scripts/firstrun-mongodb-container.sh` removed in case the error occurs again.

**Comment by scoutante112** [comment]
I try to run` docker compose exec mongodb mongosh but` I get 
```
root@Anton-Ubuntu:~/pretendo-docker# docker compose exec mongodb mongosh
OCI runtime exec failed: exec failed: unable to start container process: exec: "mongosh": executable file not found in $PATH: unknown
```
Could it be that I have changed the docker image? I need to run on nertworkweb/mongodb-no-avx as I don't have avx support.

**Comment by MatthewL246** [comment]
Unfortunately, I just don't know. I just did some quick googling and found [this repo](https://github.com/GermanAizek/mongodb-without-avx), which has some patches and a dockerfile for compiling a recent version of MongoDB without AVX. You could build this image yourself and use it in the pretendo-docker compose.yml, but it might need some modification to update mongo to the latest version and to also compile mongosh.

**Comment by scoutante112** [comment]
Okay, I understand. Is this something you can help with? Otherwise, I have to sit down and try for a while.

**Comment by MatthewL246** [comment]
Unfortunately, no, I don't have much experience with this.
I'm curious, what VPS are you using that has no AVX support? Is it ARM? I tried to run MongoDB on a raspberry pi 4 years ago and it was a huge pain, and I can only guess it's gotten worse since then.

**Comment by scoutante112** [comment]
Okay, I understand. I am a little unsure what kind of vps it is as I have received it from a close family member. I will check with him if it is possible to solve avx on vps.

**Comment by scoutante112** [comment]
A thought struck me. Is it possible to install mongodb on your vps instead of docker continer? Thinking if I should have another vps for mongodb? If so, how do I do it? Is this something you can guide me how to use another vps instead of a docker continer.

**Comment by MatthewL246** [comment]
It is definitely possible to run MongoDB on a separate server, this is how large-scale deployments with multiple servers generally do it. Here are some **untested** steps that will hopefully help you get that set up.

1. If your VPSs are on the same provider, put them in the same private network so you do not have to forward the database port to the public internet.
2. Clone this repo onto your database VPS.
3. Edit `compose.yml` on your DB VPS to delete everything except `coredns-internal` and `mongodb`.
4. Run `./scripts/firstrun-mongodb-container.sh` on the DB VPS.
5. Run `docker compose up -d` on the DB VPS.
6. If you were not able to put the 2 VPS on the same private network, you NEED to create a username and password in MongoDB using `docker compose exec mongodb mongosh` (look up how to set that up). Then, remove the `127.0.0.1:` on [this line](https://github.com/MatthewL246/pretendo-docker/blob/d18fa854690b81f587688b3ec252fbde52de3b7d/compose.yml#L74), restart `docker compose up -d`, and open port 27017 in the VPS firewall.
7. On the Pretendo VPS, remove all `mondodb` from `compose.yml` (including the service itself and the `depends_on: - mongodb`)
8. Delete [this line](https://github.com/MatthewL246/pretendo-docker/blob/d18fa854690b81f587688b3ec252fbde52de3b7d/setup.sh#L88) from `setup.sh` since MongoDB is running on the other server.
9. Basically look through all the `.env` files in `environment` and change all of the MongoDB connection strings from `mongodb:27017` to `your-db-vps-ip:27017`.

This should work in theory but it will probably require some debugging.

**Comment by scoutante112** [comment]
Okay thanks! I will check this when I have access to an ssh. I'll update how it goes after I've tested everything.

**Comment by scoutante112** [comment]
Should I remove mongo express in my Pretendo VPS?

**Comment by scoutante112** [comment]
Feels like I've forgotten something but can't figure out what it is

`(node:15) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
/app/node_modules/mongodb/lib/db.js:376
            throw new error_1.MongoAPIError(`database names cannot contain the character '${invalidChars[i]}'`);
                  ^

MongoAPIError: database names cannot contain the character '.'
    at validateDatabaseName (/app/node_modules/mongodb/lib/db.js:376:19)
    at new Db (/app/node_modules/mongodb/lib/db.js:88:9)
    at MongoClient.db (/app/node_modules/mongodb/lib/mongo_client.js:255:20)
    at _setClient (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:337:58)
    at NativeConnection.createClient (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:298:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NativeConnection.openUri (/app/node_modules/mongoose/lib/connection.js:782:5)
    at async connect (/app/dist/database.js:23:5)
    at async runAsync ([eval]:7:5) {
  [Symbol(errorLabels)]: Set(0) {}
}

Node.js v20.12.2
`

**Comment by scoutante112** [comment]
What am I doing wrong?
(node:15) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:15) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use the AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy

My mongodb string mongodb://100.65.28.70:27017/pretendo_account?replicaSet=rs&directConnection=true

**Comment by MatthewL246** [comment]
Your choice. You can either run Mongo Express on your DB VPS, or run it on your Pretendo VPS and change the configuration to use the DB VPS as the host.

**Comment by scoutante112** [comment]
Is this something I need to be concerned about?
`(node:1) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
`

**Comment by MatthewL246** [comment]
That's an expected warning.

**Comment by scoutante112** [comment]
Okay! But the thing now is that I try to access this but then I get a 185.##.##.## connection refused. Should I wait a while before trying to access port 8081?

**Comment by scoutante112** [comment]
I just got the log up. What am I doing wrong..

```
website-1                   |             triggerUncaughtException(err, true /* fromPromise */);
website-1                   |             ^
website-1                   |
website-1                   | MongooseServerSelectionError: getaddrinfo ENOTFOUND mongodb
website-1                   |     at Connection.openUri (/app/node_modules/mongoose/lib/connection.js:825:32)
website-1                   |     at Mongoose.createConnection (/app/node_modules/mongoose/lib/index.js:356:10)
website-1                   |     at Object.connect (/app/src/database.js:11:45)
website-1                   |     at Object.<anonymous> (/app/src/server.js:170:10)
website-1                   |     at Module._compile (node:internal/modules/cjs/loader:1364:14)
website-1                   |     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
website-1                   |     at Module.load (node:internal/modules/cjs/loader:1203:32)
website-1                   |     at Module._load (node:internal/modules/cjs/loader:1019:12)
website-1                   |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
website-1                   |     at node:internal/main/run_main_module:28:49 {
website-1                   |   reason: TopologyDescription {
website-1                   |     type: 'ReplicaSetNoPrimary',
website-1                   |     servers: Map(1) {
website-1                   |       'mongodb:27017' => ServerDescription {
website-1                   |         address: 'mongodb:27017',
website-1                   |         type: 'Unknown',
website-1                   |         hosts: [],
website-1                   |         passives: [],
website-1                   |         arbiters: [],
website-1                   |         tags: {},
website-1                   |         minWireVersion: 0,
website-1                   |         maxWireVersion: 0,
website-1                   |         roundTripTime: -1,
website-1                   |         lastUpdateTime: 186267046,
website-1                   |         lastWriteDate: 0,
website-1                   |         error: MongoNetworkError: getaddrinfo ENOTFOUND mongodb
website-1                   |             at connectionFailureError (/app/node_modules/mongodb/lib/cmap/connect.js:387:20)
website-1                   |             at Socket.<anonymous> (/app/node_modules/mongodb/lib/cmap/connect.js:310:22)
website-1                   |             at Object.onceWrapper (node:events:632:26)
website-1                   |             at Socket.emit (node:events:517:28)
website-1                   |             at emitErrorNT (node:internal/streams/destroy:151:8)
website-1                   |             at emitErrorCloseNT (node:internal/streams/destroy:116:3)
website-1                   |             at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
website-1                   |           cause: Error: getaddrinfo ENOTFOUND mongodb
website-1                   |               at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
website-1                   |             errno: -3008,
website-1                   |             code: 'ENOTFOUND',
website-1                   |             syscall: 'getaddrinfo',
website-1                   |             hostname: 'mongodb'
website-1                   |           },
website-1                   |           [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
website-1                   |         },
website-1                   |         topologyVersion: null,
website-1                   |         setName: null,
website-1                   |         setVersion: null,
website-1                   |         electionId: null,
website-1                   |         logicalSessionTimeoutMinutes: null,
website-1                   |         primary: null,
website-1                   |         me: null,
website-1                   |         '$clusterTime': null
website-1                   |       }
website-1                   |     },
website-1                   |     stale: false,
website-1                   |     compatible: true,
website-1                   |     heartbeatFrequencyMS: 10000,
website-1                   |     localThresholdMS: 15,
website-1                   |     setName: 'rs',
website-1                   |     maxElectionId: null,
website-1                   |     maxSetVersion: null,
website-1                   |     commonWireVersion: 0,
website-1                   |     logicalSessionTimeoutMinutes: null
website-1                   |   },
website-1                   |   code: undefined
website-1                   | }
website-1                   |
website-1                   | Node.js v18.20.2
website-1                   | Debugger listening on ws://0.0.0.0:9230/5feb6fca-8367-43aa-8095-2e62785e06ec
website-1                   | For help, see: https://nodejs.org/en/docs/inspector
website-1                   | [14:53:26] [INFO]: Setting up Middleware
website-1                   | [14:53:26] [INFO]: Setting up static public folder
website-1                   | [14:53:26] [INFO]: Importing routes
website-1                   | [14:53:27] [INFO]: Creating 404 status handler
website-1                   | [14:53:27] [INFO]: Setting up handlebars engine
website-1                   | [14:53:27] [INFO]: Starting server
```

**Comment by scoutante112** [comment]
I get an error. Have I done something wrong?

```
mitmproxy-pretendo-1 | [15:00:05.007][178.###.136.43:###] client disconnect
mitmproxy-pretendo-1 | [15:00:10.705][178.###.136.43:###] client connect
mitmproxy-pretendo-1 | [15:00:10.706] Client connection from 178.###.136.43 killed by block_global option.
mitmproxy-pretendo-1 | [15:00:10.707][178.###.136.43:###] client kill connection
mitmproxy-pretendo-1 | [15:00:10.707][178###.136.43:###] client disconnect
```

**Comment by MatthewL246** [comment]
I wasn't thinking about using a VPS outside my local network when I made this, and by default mitmproxy blocks connections coming from outside the local network. You can bypass this by passing `--set block_global=false` to mitmproxy, but be careful, because bots will be scanning the internet to try to connect to your proxy. I would recommend also setting a proxy username and password if you do this with `--set proxyauth="username:password"`.

**Comment by scoutante112** [comment]
Okay, where do I put this? And have it on a vps.

**Comment by scoutante112** [comment]
Like that! I got it, I have mongodb on a completely different server! Will see how this works with the wii u now just so thanks for all the help!

**Comment by MatthewL246** [comment]
Put it [here](https://github.com/MatthewL246/pretendo-docker/blob/d18fa854690b81f587688b3ec252fbde52de3b7d/compose.yml#L16).

Why do you keep deleting your comments? I get the emails but then the comments are gone when I check the issue.
