### ISSUE TITLE
When i try to connect co mario maker DNS error.

### ISSUE THREAD

**Issue by redmine4404** [MatthewL246/pretendo-docker#56]
I have setup my own pretendo server on a separate laptop that i use like a server and cemu to test it, and when i want to go to the world stage section of mario maker (wii u, EUR) i have a errEula pop up with the error code 106-520 (Transport::DnsError), when i close it, the game just say lock to the "please wait" screen. the mitmprxy show that only these request are made.
![image](https://github.com/MatthewL246/pretendo-docker/assets/96315018/56f15e8a-6f3f-4517-9793-da6fec815edd)

**Comment by redmine4404** [comment]
also when i try to got to the https://juxt.pretendo.network/ from my proxyied browser i have a 502 error (bad gateway), that's maybe related. I'm on the latest commit 94218bf.

**Comment by MatthewL246** [comment]
I'm not sure what the Mario Maker error is caused by, I don't know why Cemu would have a DNS error. A 502 bad gateway error in Juxt means that the server crashed, to debug that I'll need the logs from juxtaposition-ui.

**Comment by redmine4404** [comment]
after a git pull --force (for the third time), the juxtaposition website work again, it just complain that i don't have link a wiii u or 3DS. Also i have still the 106-0520 error in mario maker.

**Comment by MatthewL246** [comment]
Try re-running the setup script after pulling.

**Comment by redmine4404** [comment]
after deleting the entire pretendo-docker folder and redownload the folder, run ./setup, and compose up -d. Still get 106-0520 error.

**Comment by MatthewL246** [comment]
Alright, sounds like there is a bug in the SMM server or its configuration here. I'll investigate that when I have time soon.

**Comment by MatthewL246** [comment]
I can't reproduce this issue. Did you upload a course from the Course Maker yet? I don't think Course World will work until you upload at least one course. Otherwise, it sounds like there is an issue with your setup.

**Comment by MatthewL246** [comment]
I can see what is happening. Cemu is looking up `minio.pretendo.cc` using my system's DNS resolver instead of letting the proxy server handle it, and then it refuses to connect when it gets an NXDOMAIN. It seems that Cemu is incorrectly bypassing the configured proxy server in this case.

It works if you add this to your system's hosts file:

```
127.0.0.1 minio.pretendo.cc
```

I'll see if there's a cleaner way to do this, but that should work for now.

**Comment by redmine4404** [comment]
do i have to replace 127.0.0.1 by the ip of my server ?

**Comment by MatthewL246** [comment]
Yes, use your server's IP address. I had assumed that you were using the same computer as your server.
