### ISSUE TITLE
Error when running setup.sh

### ISSUE THREAD

**Issue by Landonb0909** [MatthewL246/pretendo-docker#89]
When running the setup.sh command through terminal on macOS, I get this output from terminal.

Error: The script ./setup.sh exited unexpectedly because an error occurred.
  ./setup.sh: line 97, in main 
    parse_arguments "$@" 
  /Users/myname/pretendo-docker/scripts/internal/framework.sh: line 364, in parse_arguments 
    for variable in "${argument_variables[@]}"; do 
((i >= 0)): exited with code 2

**Comment by MatthewL246** [comment]
Can you tell me what version of macOS and Bash (`bash --version`) you are using?

**Comment by Landonb0909** [comment]
Bash, version 3.2.57(1)-release (arm64-apple-darwin23)
macOS, Sonoma 14

**Comment by MatthewL246** [comment]
I can confirm that the scripts don't work with Bash 3.2. You can work around this by running it with Bash 4.0 or later. I'll see what I can do about making it compatible with older Bash versions.

**Comment by MatthewL246** [comment]
The scripts should now work fine on Bash 3.2.
