### ISSUE TITLE
Setup script doesn't create friends database

### ISSUE THREAD

**Issue by MatthewL246** [MatthewL246/pretendo-docker#90]
It seems that the setup script is sometimes silently failing to create a database for the friends server. This completely breaks friends.

**Comment by MatthewL246** [comment]
I believe this should be fixed in 6290a7f269ca80022777b9bf3bfb7dd64d2cdacb, but I was unable to reproduce this issue locally so I'm not entirely sure.

**Comment by ReynoldsCahoon** [comment]
How can one resolve this if the script fails to create the friends database? I keep encountering [Error 101-0502](https://pretendo.network/docs/error/101-0502) and that seems to be related to Friends.

![image](https://github.com/user-attachments/assets/58f033dc-f825-4a1f-a18a-daf945afac1b)

**Comment by MatthewL246** [comment]
@ReynoldsCahoon The friends database is stored in Postgres, not Mongo, so it won't show up in Mongo Express. You'll need to check Adminer (port 8025) to see whether it was created. The friends server logs should also show whether the problem is really a missing database or something else (if it's something else, please create a new issue for that).

**Comment by ReynoldsCahoon** [comment]
Disregard. It seems this occurs when you have not confirmed the email of new accounts. This can be done by restarting the console, and upon login, using the related 6 digit code provided in the associated email in Mailpit.
